In [5]:
## List (mutable)
list=['a','b',123,567]

In [6]:
list

['a', 'b', 123, 567]

In [7]:
list[3]

567

In [8]:
list[0]

'a'

In [10]:
## Set (mutable)
# Useful for eliminating duplicate values from a list, doing operations like intersection, difference, union
set={1,2,3,4,5}

In [11]:
set

{1, 2, 3, 4, 5}

In [13]:
set={1,3,6,1,6,4,8}

In [22]:
set

{1, 3, 4, 6, 8}

In [15]:
## Tuple (immutable)
tuple=1,2,3,4,5

In [16]:
tuple

(1, 2, 3, 4, 5)

In [17]:
tuple=()

In [18]:
tuple

()

In [19]:
type(tuple)

tuple

In [20]:
type(set)

set

In [23]:
## Dict(ionary)
# Include key(unique, immutabe)-value (any type) pair
letters={1:'a',2:'b',3:'c'}

In [24]:
letters

{1: 'a', 2: 'b', 3: 'c'}

In [25]:
type(letters)

dict

In [26]:
letters[2]

'b'

In [27]:
## Array-multidimensional array of objects of the same type
# A list of lists
# Use NumPy (Numerical Python)
import numpy as np
y=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [28]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
y>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [30]:
print(y.shape)

(3, 3)


In [33]:
#array index tools
print(y[0,0], y[2,1], y[1,0])

1 8 4


In [34]:
# create a 2 x 2 array of zeros
z=np.zeros((2,2))

In [35]:
z

array([[0., 0.],
       [0., 0.]])

In [36]:
# range of 5 integers
a=np.arange(5)
print (a)

[0 1 2 3 4]


In [38]:
# create a 4 x 5 array of 20 integers
b=np.arange(20).reshape(4,5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [39]:
# array operations
c=b+2
print(c)

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]
 [17 18 19 20 21]]


In [40]:
d=c*2
print(d)

[[ 4  6  8 10 12]
 [14 16 18 20 22]
 [24 26 28 30 32]
 [34 36 38 40 42]]


In [42]:
# elementwise multiplication of arrays
b*c

array([[  0,   3,   8,  15,  24],
       [ 35,  48,  63,  80,  99],
       [120, 143, 168, 195, 224],
       [255, 288, 323, 360, 399]])

In [43]:
# sum of all elements in array
b.sum()

190

In [44]:
# largest element in array
c.max()

21

In [45]:
# smallest element in array
c.min()

2

In [48]:
# 3 x 3 array of random numbers
e=np.random.random((3,3))
e

array([[0.10342095, 0.65691494, 0.29048607],
       [0.05633634, 0.1745395 , 0.53622091],
       [0.4338831 , 0.63427138, 0.98513885]])

In [50]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [51]:
# sum of each row
b.sum(axis=1)

array([10, 35, 60, 85])

In [52]:
# sum of each column
b.sum(axis=0)

array([30, 34, 38, 42, 46])

In [53]:
#cumulative sum of each row
b.cumsum(axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60],
       [15, 31, 48, 66, 85]], dtype=int32)

In [54]:
# index (third row, third column)
b[2,2]

12

In [55]:
## Pandas (PANel DAta) multidimensional datasets
# built on NumPy
# Two structures:
# Series (1-dimensional)
# DataFrame (2-dimensional)
import pandas as pd

In [60]:
# data can be array, scalar or dict
m={'a':2.,'b':3.,'c':4.,'d':5.}
pd.Series(m)

a    2.0
b    3.0
c    4.0
d    5.0
dtype: float64

In [65]:
# Index (object associated with 'b')
sd=pd.Series(m)
sd['b']

3.0

In [66]:
# Slice (third (2) object in series)
sd=pd.Series(m)
sd[2]

4.0

In [67]:
## DataFrame
# table of named columns of series 
# can define index (row labels) and columns (column labels)

In [69]:
# DataFrame from a series of dicts

In [75]:
# series of dicts
d={'one':pd.Series([1.,2.,3.,], index=['a','b','c']), 'two':pd.Series([1.,2.,3.,4.], index=['a','b','c','d'])}

In [76]:
d

{'one': a    1.0
 b    2.0
 c    3.0
 dtype: float64,
 'two': a    1.0
 b    2.0
 c    3.0
 d    4.0
 dtype: float64}

In [74]:
# made into a dataframe
df=pd.DataFrame(d)
df

one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [88]:
# or from arrays/lists (where index is range(n))
d={'one':[1.,2.,3.,4.], 'two':[4.,3.,2.,1.]}
df=pd.DataFrame(d)
df

one  two
0  1.0  4.0
1  2.0  3.0
2  3.0  2.0
3  4.0  1.0

In [94]:
# grab a specific column
df['two']

0    4.0
1    3.0
2    2.0
3    1.0
Name: two, dtype: float64

In [99]:
# grab specific rows
# iloc is integer position based
q=df.iloc[0]
q

one    1.0
two    4.0
Name: 0, dtype: float64

In [103]:
# by column and row
df['two'][0]

4.0

In [107]:
# Make a new column
df['three']=df['one']*df['two']
df

one  two  three
0  1.0  4.0    4.0
1  2.0  3.0    6.0
2  3.0  2.0    6.0
3  4.0  1.0    4.0

In [108]:
# Delete a column
del df['two']
df

one  three
0  1.0    4.0
1  2.0    6.0
2  3.0    6.0
3  4.0    4.0

In [126]:
# Make a new column
df['two']=df['three']/df['one']
df

one  three  four  two
0  1.0    4.0   5.0  4.0
1  2.0    6.0   8.0  3.0
2  3.0    6.0   9.0  2.0
3  4.0    4.0   8.0  1.0

In [129]:
# stats on dataframe
df.describe()

one     three      four       two
count  4.000000  4.000000  4.000000  4.000000
mean   2.500000  5.000000  7.500000  2.500000
std    1.290994  1.154701  1.732051  1.290994
min    1.000000  4.000000  5.000000  1.000000
25%    1.750000  4.000000  7.250000  1.750000
50%    2.500000  5.000000  8.000000  2.500000
75%    3.250000  6.000000  8.250000  3.250000
max    4.000000  6.000000  9.000000  4.000000

In [132]:
# sort by values of column 'two'
df.sort_values(by='two')

one  three  four  two
3  4.0    4.0   8.0  1.0
2  3.0    6.0   9.0  2.0
1  2.0    6.0   8.0  3.0
0  1.0    4.0   5.0  4.0

In [135]:
# get values greater than 2 in column 'one'
df[df.one>2]

one  three  four  two
2  3.0    6.0   9.0  2.0
3  4.0    4.0   8.0  1.0

In [137]:
# new copy of dataframe
# add a new column 'five'
df2=df.copy()
df2['five']=[3,6,9,12]
df2

one  three  four  two  five
0  1.0    4.0   5.0  4.0     3
1  2.0    6.0   8.0  3.0     6
2  3.0    6.0   9.0  2.0     9
3  4.0    4.0   8.0  1.0    12

In [138]:
# grab only the rows from 'five' with 6 or 12
df2[df2['five'].isin([6,12])]

one  three  four  two  five
1  2.0    6.0   8.0  3.0     6
3  4.0    4.0   8.0  1.0    12

In [139]:
# group by values in 'three'
df2.groupby('three')

In [141]:
# sum the values in those groups
df2.groupby('three').sum()

one  four  two  five
three                      
4.0    5.0  13.0  5.0    15
6.0    5.0  17.0  5.0    15